### ISSUE TITLE
Inquiry About Column Definitions in the new_york_ny.npz Dataset

### ISSUE THREAD

**Issue by God-YYB** [baixianghuang/travel#2]
Dear Baixiang Huang,

I hope this message finds you well. I recently discovered your dataset, new_york_ny.npz, on GitHub and am very interested in utilizing it. However, I have some specific questions regarding the data that I hope you can help clarify.

①、Column Definitions for x:

I noticed that x consists of 12 columns (columns 0 to 11), and these features seem to relate to urban attributes, such as road types and weather conditions. Could you please provide the specific meanings for each column?
Example data:
| 0    | 1    | 2    | 3    | 4    | 5    | 6    | 7    | 8    | 9    | 10   | 
| ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- |
| 3    | 0    | 0    | 1    | 0    | 0    | 0    | 0    | 0    | 0    | 0    |

②、Feature Definitions for edge_attr:

The edge_attr contains 18 features, which may relate to road lengths, traffic volumes, etc. Could you please specify what each of these 18 features represents?
Example data:
| 0       | 1    | 2    | 3    | 4    | 5    | 6    | 7    | 8    | 9    | 10   | 11   | 12   | 13   | 14   | 15   | 16   | 17   |
| ------- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- |
| 254.709 | 1    | 0    | 0    | 1    | 0    | 0    | 1    | 0    | 0    | 0    | 0    | 0    | 0    | 0    | 0    | 0    | 0    |

③、Clarification on edge_attr_dir:
Does the first and second column of edge_attr_dir represent increments in the x and y directions, respectively?

④、Angle Information in edge_attr_ang:
The edge_attr_ang indicates angle attributes for each edge, consisting of three angle measurements. Could you please explain what these three angles specifically represent?

Thank you for taking the time to address these questions. I look forward to your response.

Best regards,

Yibo Yuan

**Comment by baixianghuang** [comment]
Please refer to `code/detailed_node_and_edge_features.ipynb` for the detailed feature names corresponding to each feature in `x` and `edge_attr`. Note that different cities have varying node and edge features due to occasional incompleteness in OSM data, which may result in some missing features. To check the features for other cities, you will need to rerun the notebook with the specified city. Additionally, running the notebook requires the data file `bing_crash_geocoded.csv`, which can be found at https://drive.google.com/file/d/10-WeXrZwPoSUwnkBWmcQPIX0s7z8VcWK/view?usp=sharing
